BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Bien" (
	"ID_Bien"	INTEGER NOT NULL,
	"Nombre"	TEXT NOT NULL,
	"ID_Categoria"	INTEGER NOT NULL,
	"Estado"	TEXT NOT NULL,
	"Detalle"	TEXT,
	"ID_Ubicacion"	INTEGER NOT NULL,
	"Eliminado" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID_Bien" AUTOINCREMENT),
	FOREIGN KEY("ID_Categoria") REFERENCES "Categoria"("ID_Categoria"),
	FOREIGN KEY("ID_Ubicacion") REFERENCES "Ubicacion"("ID_Ubicacion")
);
CREATE TABLE IF NOT EXISTS "Categoria" (
	"ID_Categoria"	INTEGER NOT NULL,
	"Nombre"	TEXT NOT NULL,
	"Eliminado" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID_Categoria" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Ubicacion" (
	"ID_Ubicacion"	INTEGER NOT NULL,
	"Nombre"	TEXT NOT NULL,
	"Es_Editable"	INTEGER NOT NULL DEFAULT 1,
	"Eliminado"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID_Ubicacion" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "EventoTrazabilidad" (
	"ID_Evento"	INTEGER NOT NULL,
	"ID_Bien"	INTEGER NOT NULL,
	"Fecha"	TEXT NOT NULL DEFAULT (datetime('now')),
	"TipoEvento"	TEXT NOT NULL,
	"Eliminado" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID_Evento" AUTOINCREMENT),
	FOREIGN KEY("ID_Bien") REFERENCES "Bien"("ID_Bien")
);
CREATE TABLE IF NOT EXISTS "Solicitud" (
	"Num_Solicitud"	INTEGER NOT NULL,
	"Estado"	TEXT NOT NULL,
	"Destino"	INTEGER NOT NULL,
	"Fecha_Solicitud"	TEXT NOT NULL DEFAULT (datetime('now')),
	"Descripcion"	TEXT NOT NULL,
	"Eliminado" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("Num_Solicitud" AUTOINCREMENT)
	FOREIGN KEY("Destino") REFERENCES "Ubicacion"("ID_Ubicacion")
);
CREATE TABLE IF NOT EXISTS "Usuario" (
	"ID_Usuario"	INTEGER NOT NULL,
	"Nombre_Usuario"	TEXT NOT NULL,
	"Contraseña"	TEXT NOT NULL,
	"Rol"	TEXT NOT NULL,
	"Eliminado" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ID_Usuario" AUTOINCREMENT)
);
COMMIT;
